console.log("this file ir is inside git")
console.log( "this file should be inside the gitignore")
console.log( "this file should be inside the gitignore")
console.log( "this file should be inside the gitignore")
console.log( "this file should be inside the gitignore")
console.log( "this file should be inside the gitignore")
console.log( "this file should be inside the gitignore")